# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Opt Web - Desenvolvendo Para Te Impulsionar!"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Opt Web - Desenvolvendo Para Te Impulsionar!"


# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: assets
  style: compressed

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://optweb.github.io"

# The shortname for your Disqus site to enable comments.
disqus: "optweb"

# Author information - author info at the bottom of the post
author_name: "OPT WEB"

# Social links in the site footer
twitter_username: "optweb"
facebook_username: "optweb"
instagram_username: "opt.web"
github_username: "optwebdev"
linkedin_username: "optweb"
email: "contato.optweb@gmail.com"

permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : rouge

plugins:
  - jekyll-gravatar
  - jekyll-redirect-from

